# Generated by Django 6.0.4 on 2026-06-14 09:22

from django.db import migrations


def copy_pokemons_to_postPokemons(apps, schema_editor):
    PostPokemon = apps.get_model('pokemon_entities', 'PostPokemon')
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    for pokemon in Pokemon.objects.all():
        PostPokemon.objects.get_or_create(id=pokemon.id, title=pokemon.title, image=pokemon.image)


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_postpokemon'),
    ]

    operations = [
        migrations.RunPython(copy_pokemons_to_postPokemons)
    ]
