# Generated by Django 6.0.4 on 2026-06-14 10:11

from django.db import migrations


def copy_pokemons_to_newPokemons(apps, schema_editor):
    NewPokemon = apps.get_model('pokemon_entities', 'NewPokemon')
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    for pokemon in Pokemon.objects.all():
        NewPokemon.objects.get_or_create(id=pokemon.id,
                                         title_ru=pokemon.title,
                                         image=pokemon.image,
                                         description=pokemon.description,
                                         )


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_newpokemon'),
    ]

    operations = [
        migrations.RunPython(copy_pokemons_to_newPokemons)
    ]
