# Generated by Django 6.0.4 on 2026-06-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20260614_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.newpokemon'),
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
