# Generated by Django 6.0.4 on 2026-06-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_alter_pokemonentity_pokemon_delete_pokemon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPokemon',
            new_name='Pokemon',
        ),
    ]
